### ISSUE TITLE
Bonestorms should be added.

### ISSUE THREAD

**Issue by Shadowclaimer** [TeamMetallurgy/Atum#110]

**Comment by Shadowclaimer** [comment]
![bonestorm](https://cloud.githubusercontent.com/assets/2214143/10600651/363049cc-76da-11e5-946c-89bd011fd200.png)

**Comment by Shadowclaimer** [comment]
Uses Blaze model, shoots bones. Might need projectile art.

**Comment by GirafiStudios** [comment]
I started on this, mostly done. Just needs to talk to Shadowclaimer about a few details.

**Comment by Shadowclaimer** [comment]
Bonestorm
Class: Undead
Speed 2
HP 20
Dam 2
EXP 8
Drops 1-2 Bone (25%)
Shoots Spinning Bones with slightly higher knockback
Immune to Fire

**Comment by Shadowclaimer** [comment]
Bonestorm Progress Report

Noted changes as we tested them
-Added transparency to a few areas of the mob texture
-Damage went to 4
-They drop Dusty Bones instead of Bones (and Forsaken/Dusty Skeletons drop Dusty Bones now as well)
-Dusty Bones make 1 Bonemeal instead of 3
-They use the sound effects of Skeletons mixed with Skeleton Horses

Things to do still:
-Rotating Bone Projectiles (might require a render)
-Dusty effect particles
-Bonestorms fly under the ground occasionally
-Bones sometimes get stuck in the air
-Desert Wolves should tame using Dusty Bones

Latest test version:
https://slack-files.com/T06PCHHA6-F0CSUSFTR-e969f14468

Major thanks to @GirafiStudios for knocking this one out of the park so far!
