### ISSUE TITLE
New Biomes

### ISSUE THREAD

**Issue by Shadowclaimer** [TeamMetallurgy/Atum#140]
Plan to expand the biomes of Atum to include a variety of terrain types and not just the generic one that we have. Most of which can easily be made with some tweaks to normal biomes and replacing the generated blocks with Atum blocks.

**Sand Plains** (Plains) - Sand as far as you can see, few dead trees.
**Sand Dunes** (Plains M) - Gently rolling hills of sand, no palm trees
**Sand Hills** (Hills) - More extreme and larger hills of sand
**Limestone** (ExtremeHills+M) - Mountains Limestone Mountains, some sand, few dead trees
**Limestone Crags** (IcePlainSpikes) - Spires of Limestone, both large and small, litter the landscape, ravines/canyons
**Oasis** (Swampland) - Pool of water surrounded by Palm trees and fertile soil. Replaces structure-style Oasis.
**Dried River** (River) - Former river, cracked dirt and sand everywhere, no water.
**Dead Oasis** (Swampland) - Former oasis, cracked dirt and sand with dead trees around the edge, no water.
**Ruined City** (Plains) - Sand Plains with tons of broken walls jutting out of the dunes

**Comment by allaryin** [comment]
Sigh. Hmm...

**Comment by Shadowclaimer** [comment]
Muahahhaha

**Comment by Shadowclaimer** [comment]
Split into #209, #210, #211, #212, #213, #214, #215, #216, #217
