### ISSUE TITLE
Desert Wolves should be tameable

### ISSUE THREAD

**Issue by Shadowclaimer** [TeamMetallurgy/Atum#143]
Using the new Dusty Bone that is in Girafi's soon to be coming PR.

**Comment by GirafiStudios** [comment]
Started working on this.

**Comment by Shadowclaimer** [comment]
![desertwolf_tame](https://cloud.githubusercontent.com/assets/2214143/10652868/0f4b0c80-7828-11e5-9503-c0c30db2a6d9.png)

![desertwolf_collar](https://cloud.githubusercontent.com/assets/2214143/10652907/451595ec-7828-11e5-957c-495ba6d5dd1d.png)
