### ISSUE TITLE
Wolves aren't being aggressive by default

### ISSUE THREAD

**Issue by Shadowclaimer** [TeamMetallurgy/Atum#184]
They're acting rather oddly and not attacking all the time.

**Comment by GirafiStudios** [comment]
They are agressive by default, but they are indeeed acting weird. Might related to #145

**Comment by Shadowclaimer** [comment]
That was my thought as well. I walked into a pack of 5 of them last night and they didn't attack me until I started walking away from them. It was definitely an on and off thing for some reason.
