### ISSUE TITLE
Portal only opens while in creative or adventure mode.

### ISSUE THREAD

**Issue by alextpedro** [TeamMetallurgy/Atum#21]
As it says on the tin. Can't open the portal unless set to creative or adventure modes. Config says it should.

**Comment by alextpedro** [comment]
http://pastebin.com/tEM86m8R

**Comment by Adaptivity** [comment]
Can confirm this on latest Forge and with latest Atum.

**Comment by Adaptivity** [comment]
http://i.imgur.com/thO9AoX.jpg this portal. It's creates fine in creative but in survival no.

**Comment by lclc98** [comment]
That is weird, its working fine for me, I am not sure, il keep looking into it

**Comment by Glassmaker** [comment]
Make sure it's two layers of 5x5

![2015-02-10_11 00 55](https://cloud.githubusercontent.com/assets/5352172/6123656/4de8ffa8-b116-11e4-87c5-d27d5c145917.png)
