### ISSUE TITLE
Custom names for Loot

### ISSUE THREAD

**Issue by Adaptivity** [TeamMetallurgy/Atum#25]
@Glassmaker something that you've done for ExtraTiC. You can see here: https://github.com/TeamMetallurgy/Atum/blob/master/src/main/resources/assets/atum/lang/ru_RU.lang#L253 that loot names are shortened(They have "." instead of normal endings). So, I need to manually add: "item.loot.dirty.idol.name=Dirty Idol" and etc names for everything.

**Comment by Glassmaker** [comment]
:3

**Comment by Adaptivity** [comment]
Thanks!

**Comment by Glassmaker** [comment]
You're welcome :)
