### ISSUE TITLE
Fix doubled Mighty I

### ISSUE THREAD

**Issue by Adaptivity** [TeamMetallurgy/Atum#27]
Since you @Glassmaker fixing Atum :) See here: https://github.com/TeamMetallurgy/Atum/blob/master/src/main/resources/assets/atum/lang/en_US.lang#L256

**Comment by Adaptivity** [comment]
Note from IRC: Anhurs Might actually speeds up player. So, it's tooltip is incorrect and Horus Soaring has completely different tooltip.

**Comment by Glassmaker** [comment]
Looking at Anhurs Might in the old code in Keithy's repo is slowing the player by 25%, so the tooltip is correct and the effect is wrong.

Horus Soaring have faster arrows, and the tooltip shows Velocity I, guess localization wasn't implemented for Horus Soaring.

**Comment by Adaptivity** [comment]
So, now you should fix it :)
