### ISSUE TITLE
Atum Night/Day should be equal durations

### ISSUE THREAD

**Issue by Adaptivity** [TeamMetallurgy/Atum#35]
Tried to set time to dawn through NEI but it's still night... and day 1 never changes to day 2. Related to: https://github.com/RebelKeithy/Atum/issues/34

**Comment by Glassmaker** [comment]
Interesting, I thought it's intentionally made double the time to make it harder at night. there for "/time set night" and NEI won't work as intended.

/time set 0 = Dawn
/time set 13000 = midday (Vanilla's night)
/time set 26000 = sunset
/time set 39000 = midnight

**Comment by Adaptivity** [comment]
Maybe you can make the day/night equal (since it was the original concept) and add config option for longer night?

**Comment by lclc98** [comment]
Night has always been double, we intended to add mobs that only spawn at night and at day but was never complete, so it got removed

**Comment by Shadowclaimer** [comment]
Night should be twice as long as day, however a related issue is #66

**Comment by Shadowclaimer** [comment]
Breakdown of Atum Days (or how they should be.)

Vanilla MC Overworld Day - 24,000 Ticks
Atum Day - 48,000 Ticks
Atum Daytime - 16,000 Ticks
Atum Nighttime - 32,000 Ticks
