### ISSUE TITLE
Library's spawn rate

### ISSUE THREAD

**Issue by ultrasn0w** [TeamMetallurgy/Atum#39]
Mabe you should lower the spawn rate of palaces.
With the latest version they seem to be everywhere :)
https://i.imgur.com/9tg1m02.jpg

Also, small thing just recognized, the biome name isn't localozed properly (top left corner).

**Comment by Glassmaker** [comment]
That's odd, the spawn rate for the palace is one in 320 chunks, didn't find them that close while testing o.o

Can you check around and see if there are more close by?

Looks like there is no biome name localization functionality, So I might change the biome name to English after making sure there is no way to localize biome names.

**Comment by Adaptivity** [comment]
I know no mods which have localization for biomes, even vanilla doesn't localize biome names.

**Comment by Glassmaker** [comment]
Okeo, thanks Adaptivity. :)
Going to change it to English until there is localization support :)

**Comment by ultrasn0w** [comment]
I flew around a bit more, only a few chunks away I found another one and could already see the next one at the view distance border. I do not think this is one in 320 chunks :)

**Comment by Glassmaker** [comment]
Umm.. okeo, then going to bump it up :)
