### ISSUE TITLE
Limestone Large Bricks

### ISSUE THREAD

**Issue by Xltimus** [TeamMetallurgy/Atum#42]
Forge 10.13.2.1291
Atum-1.7.10-0.6.57

-"Limestone Large Bricks" (both generated and player-crafted) are unable to be broken by traditional tools such as pickaxes.
-"Limestone Large Bricks" are unable to be moved by pistons.
-"Limestone Large Bricks" can easily be blown up by tnt.

I understand that there's a reason for the behavior of this particular block regarding the structures. (The exploding thing might be an oversight?) But for a typical player using this block (likely for decorative purposes), these behaviors aren't exactly ideal. I suppose making a block dedicated for the structures and just use metadata for the various variants of brick textures could work though.

**Comment by HanatakeYurii** [comment]
I would suggest to make an "hardened" version of this block using a different metadata and make it almost unbreakable, so in this there is no more need to protect specific structures with heavy algorithmes. Many other mods make their dungeons this way (ex: Twilight Forest for Minotaur Mazes)
