### ISSUE TITLE
Too late registering of Blocks & Items (PRE-Init // Init)

### ISSUE THREAD

**Issue by ultrasn0w** [TeamMetallurgy/Atum#45]
Hello again,
I recently wrote about population of other mods features, @GregoriusT has included support for the Atum dimension to let GregTech ores generate there, however Atum's Blocks and Items are registered  within Init and not (as it would be correct) within PRE-Init, I hope this will get fixed since it makes cross Mod compatibility more difficult if not impossible.

Greetings
ultrasn0w

**Comment by Glassmaker** [comment]
Interesting, Forge used to print a warning if there an item or block registration not in Pre-init, 
guess that was changed.

**Comment by GregoriusT** [comment]
Lol, you must be kidding me, Git. Did you really change the location
of where the Function starts and ends without changing the content? XD

2015-03-19 14:26 GMT, Glassmaker <notifications@github.com>:

**Comment by ultrasn0w** [comment]
May I know how I can build the latest version for myself?
Wanted to test if it works now.
I tried, but running gradlew.bat was not enough :(

**Comment by odininon** [comment]
@GregoriusT, yes why wouldn't it work that way? It only compares the lines, not what the lines contain. This is what makes git very power and doesn't have to adapt to the content.

**Comment by GregoriusT** [comment]
Sure, but I did not think that the Code would have been written for
this exact coincedence to happen. ^^

2015-03-26 1:01 GMT+01:00, Freyja <notifications@github.com>:

**Comment by odininon** [comment]
@Glassmaker is just adaptive like that. :+1:

**Comment by odininon** [comment]
@ultrasn0w you need to run ./gradlew.bat setupCIWorkspace build

Just a disclaimer, if you edit the code in any way and experience issues in result of those, we are not reliable, but we will offer help :)

**Comment by ultrasn0w** [comment]
@odininon Thank you, also the Issue seems to be fixed.
In terms of changing the code: I mean, its the most obvious thing ever :D I'm not such kind of a person.

**Comment by odininon** [comment]
Wasn't applying that you were, just had to throw it out there. I would say our lawyers tell us to say it, but who am I kidding we don't have lawyers.... or even a cool office.
