### ISSUE TITLE
Empty...

### ISSUE THREAD

**Issue by jacfalcon0** [TeamMetallurgy/Atum#46]
A friend and I are playing on my SMP world via LAN, and we came through the portal only to find desert. We dug deep, explored all over, and there's nothing but strange sand, stone, and some Botania mushrooms in the caves. We waited until night and no mobs spawned. Is this an error?

**Comment by Glassmaker** [comment]
Hi, sorry about the delay in replying.

Try to check if there is a biome id conflict, as it works fine over here on SMP / SSP.

**Comment by jacfalcon0** [comment]
I switched to a different biome number and updated a bunch of my mods, and then flew very, very far and started running into mobs, trees, ores, etc. Not sure what the issue was. There's definitely several hundred chunks with nothing but the two sand blocks and terrain variation.

**Comment by Glassmaker** [comment]
Guess because the world already generated so it uses the other biome instead of atum's biome.

Try deleting the dimension file to regenerate the dimension, remember to take a backup of your save folder before doing this.
