### ISSUE TITLE
[Suggestion] Remove stained glass

### ISSUE THREAD

**Issue by Xen1290** [TeamMetallurgy/Atum#52]
Currently is useless, vanilla has already stained glass. Also Forestry has done the same thing. 
@Glassmaker 
ForestryMC/ForestryMC#809

**Comment by Glassmaker** [comment]
But ours a different type of glass (Crystal Glass) which you can get from smelting strange sand from the mod.

And, the stained crystal glass ones have different design than vanilla so you have extra decorations.

![2015-03-01_18 28 38](https://cloud.githubusercontent.com/assets/5352172/10529074/7ccaa588-73a3-11e5-8778-e8cd962970b0.png)

I think we will be keeping our glass type for the current time.

**Comment by Shadowclaimer** [comment]
I stand with Glassy on that one. No reason to remove it.

**Comment by Glassmaker** [comment]
Guess it's settled, closing the issue.

**Comment by Xen1290** [comment]
Ok, no problems! Thanks for the answers
