### ISSUE TITLE
Shading issues on Half-Slabs and Slab Blocks.

### ISSUE THREAD

**Issue by Shadowclaimer** [TeamMetallurgy/Atum#60]

**Comment by Shadowclaimer** [comment]
Opening, was not fixed by PR.

![2015-10-21_17 59 52](https://cloud.githubusercontent.com/assets/2214143/10651451/9fbb50dc-781d-11e5-8fe8-50301c375dcb.png)

**Comment by jaredlll08** [comment]
Was that placed in the world before? or did you place it in this version?

**Comment by Shadowclaimer** [comment]
I placed these but the issue is also occurring in preplaced blocks when I explored in Atum.
