### ISSUE TITLE
Pharaoh Chests sometimes bug out and don't have loot and instead replay spawn effect.

### ISSUE THREAD

**Issue by Shadowclaimer** [TeamMetallurgy/Atum#64]

**Comment by Shadowclaimer** [comment]
Might be related to cross-chunk stuff. Since all three times it happened to me I had died against the Pharaoh and had to return to the Pyramid, killed Pharaoh, then opened chest and had it happen.

**Comment by Glassmaker** [comment]
Reopening the Issue, as it's not fixed.
