### ISSUE TITLE
Dead Trees are not spawning.

### ISSUE THREAD

**Issue by Shadowclaimer** [TeamMetallurgy/Atum#67]

**Comment by GirafiStudios** [comment]
There is no code or textures related to dead trees at all.

**Comment by Shadowclaimer** [comment]
Might've been one of the features we "lost" in the downgrade.

Let me find the stuff.

![image](https://cloud.githubusercontent.com/assets/2214143/10623467/497eaeb4-775d-11e5-82e0-033e40fb7a33.png)

They're effectively trees that have no leaves, 11 or so tall, couple truck branches. Nothing fancy.

I'll get the art for planks and such in a bit.

**Comment by Glassmaker** [comment]
Want them to generate on fertile soil and dirt or just on sand?

**Comment by Shadowclaimer** [comment]
Just sand if you don't mind.

Design should be something akin to these, just giant dead clumps of wood reaching for the sun.

http://www.nocaptionneeded.com/wp-content/uploads/2008/09/desert-trees.png

**Comment by Shadowclaimer** [comment]
Thanks Glassy =D

**Comment by Glassmaker** [comment]
How do these look? :)

![2016-01-19_21 06 47](https://cloud.githubusercontent.com/assets/5352172/12427539/e6a781a4-bef0-11e5-9e96-af25267675f3.png)
![2016-01-19_21 07 29](https://cloud.githubusercontent.com/assets/5352172/12427540/e6a83d2e-bef0-11e5-83b0-ec883ab1b618.png)
![2016-01-19_21 08 32](https://cloud.githubusercontent.com/assets/5352172/12427541/e6adc410-bef0-11e5-8fda-83df6899fbc7.png)

**Comment by Shadowclaimer** [comment]
Decent bit smaller, maybe half the size, but pretty close =D

Like 7 tall at absolute most, 5-6 normal.

**Comment by Glassmaker** [comment]
How about now? :3

![2016-01-19_21 20 51](https://cloud.githubusercontent.com/assets/5352172/12427856/9d056ca8-bef2-11e5-82db-12b8e72c958f.png)
![2016-01-19_21 21 02](https://cloud.githubusercontent.com/assets/5352172/12427857/9d0b47ae-bef2-11e5-98dc-cd1d939de30a.png)
![2016-01-19_21 21 12](https://cloud.githubusercontent.com/assets/5352172/12427858/9d0ce352-bef2-11e5-84b5-9bdf1639e293.png)

**Comment by GirafiStudios** [comment]
Number 2 looks pretty wonky. Maybe making it so there is at least 3 logs straight up, before it goes into branches ? :)

**Comment by Glassmaker** [comment]
@GirafiStudios it's similar to the photo, they are all wonky from the bottom :D

**Comment by Shadowclaimer** [comment]
Looks great. I'd advise making them default with at least one horizontal off the base, and maybe up to 3 or 4. They're really going to look wonky regardless until I get a "branch" minor bit done that matches it that can hang off randomly.

Here's some 2D suggestions.

![image](https://cloud.githubusercontent.com/assets/2214143/12428354/20602354-beb2-11e5-971b-cdef0a8a2a1b.png)

**Comment by Glassmaker** [comment]
Done :)

![2016-01-19_22 05 59](https://cloud.githubusercontent.com/assets/5352172/12429017/0e23f656-bef9-11e5-9332-1fb692de7d6d.png)
![2016-01-19_22 06 05](https://cloud.githubusercontent.com/assets/5352172/12429018/0e26f770-bef9-11e5-8c3f-65c69e342525.png)
![2016-01-19_22 06 15](https://cloud.githubusercontent.com/assets/5352172/12429019/0e2c342e-bef9-11e5-851a-4555265d52ca.png)
![2016-01-19_22 06 38](https://cloud.githubusercontent.com/assets/5352172/12429020/0e2ee0f2-bef9-11e5-9581-9c75474c6f77.png)
![2016-01-19_22 09 31](https://cloud.githubusercontent.com/assets/5352172/12429090/615e28f0-bef9-11e5-94e9-c47d96774542.png)

**Comment by Shadowclaimer** [comment]
Great! =D

Eventually I'll find a way to make them less wonky lol
