### ISSUE TITLE
Ruin Chests use Dungeon Loot as opposed to their own table. Shouldn't have Saddles and such.

### ISSUE THREAD

**Issue by Shadowclaimer** [TeamMetallurgy/Atum#69]

**Comment by Shadowclaimer** [comment]
Might simply be that Saddles and Cocoa Beans were added by default when we made the loot tables. Regardless those two things (and Bread) shouldn't really be found in ruin chests.

**Comment by lclc98** [comment]
The current loot after removing what you said, want any others removed?: 
- Flax seeds
- Stick
- Date
- Bone
- Strange sand
- Scimitar
- Wheat seeds
- Leather
- iron ingot
- gold ingot 
- diamond
- enchanted book

**Comment by Shadowclaimer** [comment]
Wheat Seed definitely. Rest should be fine.

**Comment by GirafiStudios** [comment]
After the plans of adding camels, saddles might be a good thing to keep?

**Comment by Shadowclaimer** [comment]
I think we'll still keep saddles out of the loot tables, they're way too common, we can leave Leather or such and people can just make their own.
