### ISSUE TITLE
Gravel (or a Gravel variant that gives Flint) should spawn in this world.

### ISSUE THREAD

**Issue by Shadowclaimer** [TeamMetallurgy/Atum#75]

**Comment by wiiv** [comment]
Maybe spawn rivers (rare) which would have River Sand along their flow, and it drops flint (1-2).

**Comment by Shadowclaimer** [comment]
I was considering rivers, but the issue is Atum is supposed to be a "dead" world, almost post-apocalyptic when you start discovering the story so water sources like that would be super, super rare, and I'd like Flint to be a little more common than that.

I think a simply gravel variant will suffice, it'll also spice up the underground a little more.

**Comment by wiiv** [comment]
Dry river sand then. ;)

**Comment by Shadowclaimer** [comment]
Dry Rivers are a biome I'd definitely love to have eventually. I actually wanted a Dry Ocean biome but figured that'd be masochistic.

**Comment by Shadowclaimer** [comment]
![limestonegravel](https://cloud.githubusercontent.com/assets/2214143/10684555/acadbe56-791c-11e5-9300-71f83964e060.png)

Texture Complete. "Limestone Gravel" will simply be its name.
