### ISSUE TITLE
Dead Wood needs its own Stairs, Slabs, Fences, Door, and Ladder.

### ISSUE THREAD

**Issue by Shadowclaimer** [TeamMetallurgy/Atum#79]

**Comment by Shadowclaimer** [comment]
![deadwooddoorupper](https://cloud.githubusercontent.com/assets/2214143/10684860/3d2c1d3a-7920-11e5-9cdb-e2ab4b8dfe92.png)
![deadwoodhatch](https://cloud.githubusercontent.com/assets/2214143/10684859/3d2a99c4-7920-11e5-8a6c-3236ddc3df9d.png)
![deadwoodladder](https://cloud.githubusercontent.com/assets/2214143/10684862/3d33b9c8-7920-11e5-82db-900b91301b9e.png)
![deadwoodplank](https://cloud.githubusercontent.com/assets/2214143/10684864/3d34d650-7920-11e5-92c6-0404d69c3ebc.png)
![deadwoodcrate](https://cloud.githubusercontent.com/assets/2214143/10684861/3d3327d8-7920-11e5-8b74-1c39b46c0bc1.png)
![deadwooddoorlower](https://cloud.githubusercontent.com/assets/2214143/10684863/3d33d62e-7920-11e5-9271-279bf65761f2.png)

**Comment by Glassmaker** [comment]
Texture for door as an Item is missing. :)

**Comment by Shadowclaimer** [comment]
Oops let me do that real quick.

**Comment by Glassmaker** [comment]
Also, are Crates have inventories or just blocks?

**Comment by Shadowclaimer** [comment]
Inventories, they're smaller chests without an animation or such at the
moment. I was going to shave the top pixel off and hinge it and add a
"hole" texture for the top but haven't gotten to it.

For now just no animation, single chest size basically.

**Comment by Shadowclaimer** [comment]
![image](https://cloud.githubusercontent.com/assets/2214143/12430477/d0d02d8c-bebd-11e5-9069-d43a96a36161.png)

There's the door art for items.

**Comment by Glassmaker** [comment]
Awesome thanks :)

**Comment by Glassmaker** [comment]
Need stick textures for both types of woods, as it's a recipe component for Ladders, Fences, and Fence Gates.

**Comment by Shadowclaimer** [comment]
![image](https://cloud.githubusercontent.com/assets/2214143/12481120/f8d32250-c014-11e5-95dd-14922f8407dc.png)

![image](https://cloud.githubusercontent.com/assets/2214143/12481155/2a9f243c-c015-11e5-8865-65ad996caf8f.png)

![image](https://cloud.githubusercontent.com/assets/2214143/12481253/cfefa2e0-c015-11e5-988d-013445781205.png)

Torches if you need them too.

**Comment by Glassmaker** [comment]
Thanks :D

**Comment by Shadowclaimer** [comment]
Yea sorry about no transparency, at work with no access to tools to add it lol

**Comment by Glassmaker** [comment]
no worries :)
