### ISSUE TITLE
Palm Wood needs its own Stairs, Slabs, Fences, Door, and Ladder.

### ISSUE THREAD

**Issue by Shadowclaimer** [TeamMetallurgy/Atum#80]

**Comment by Shadowclaimer** [comment]
![image](https://cloud.githubusercontent.com/assets/2214143/10684747/06a160b4-791f-11e5-9de8-7aeb445c8154.png)

palm hatch

![image](https://cloud.githubusercontent.com/assets/2214143/10684752/166f675c-791f-11e5-98f9-c1f8c0995d3b.png)

palm door

![palmladder](https://cloud.githubusercontent.com/assets/2214143/10684772/4e1ce710-791f-11e5-8b4a-3d32c55de9d2.png)

palm ladder

**Comment by Glassmaker** [comment]
Texture for door as an Item is missing. :)
